# alacritty.toml

import = [ "~/.config/alacritty/themes/solarized_dark.toml" ]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 120, lines = 48 }
dynamic_title = true
padding = { x = 16, y = 16}
option_as_alt = "Both"

[colors]
draw_bold_text_with_bright_colors = false

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "BlexMono Nerd Font Mono", style = "Regular" }
bold = { family = "BlexMono Nerd Font Mono", style = "Bold" }
italic = { family = "BlexMono Nerd Font Mono", style = "Regular Italic "}
size = 18.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[debug]
persistent_logging = false

# EOF
