# .envcfg/zsh/zshrc (linked from ~/.zshrc)

export CLICOLOR=1
export HISTFILE=~/.zsh_history
export HISTSIZE=10000

alias vi="nvim"
alias vim="nvim"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Applications/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Applications/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Applications/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Applications/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
